#!/bin/bash

# Usage:
#   com/something/foo -> foo@something.com
#   baz/bar/foo/user.tag -> user.tag@foo.bar.baz

echo $1 \
| tr '/' ' ' \
| awk '{ for(i = NF; i > 1; i--) printf("%s ", $i); print $1; }' \
| sed 's/ /@/' \
| tr ' ' '.'
